# Generated by Django 2.2.6 on 2019-11-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='highlighted',
            field=models.TextField(null=True),
        ),
    ]
