# Generated by Django 2.2.6 on 2019-11-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='userId',
        ),
    ]
