# Generated by Django 3.0.4 on 2020-03-29 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200307_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='average_rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
