# Generated by Django 2.2.6 on 2019-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_meal_counttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='average_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
