# Generated by Django 2.2.6 on 2019-11-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_meal_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrate',
            name='mealId',
        ),
    ]
