# Generated by Django 2.2.6 on 2019-11-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_mealrate_mealid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrate',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='report',
            name='userId',
        ),
    ]
